name: Generate Debug Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate debug keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore debug.keystore \
            -alias androiddebugkey \
            -storepass android \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Create Base64 file
        run: |
          base64 -w0 debug.keystore > debug.keystore.base64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: |
            debug.keystore
            debug.keystore.base64
